name: Rui Zhang Blog
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:categories/:year/:month/:day/:title
categories: [cpp, java, oop, algorithms, datastructures, multithreading, functionalprogramming, misc]
